[package]
name = "wallet-cli"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "develop" }
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
tokio = { version = "0.2", features = ["full"] }
dialoguer = "0.7"
console = "0.13"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
once_cell = "1.4"
serde_json = "1.0"
futures = "0.3"

[profile.release]
lto = true
codegen-units = 1
